name: CI
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - run: dotnet restore src/NetMQ.sln
    - name: build
      run: dotnet build src/NetMQ.sln /p:Configuration=Release /verbosity:minimal
    - name: test net6.0
      run: dotnet test -v n -p:ParallelizeTestCollections=false --configuration Release --no-build -f net6.0 src/NetMQ.Tests/NetMQ.Tests.csproj
    - name: test net8.0
      run: dotnet test -v n -p:ParallelizeTestCollections=false --configuration Release --no-build -f net8.0 src/NetMQ.Tests/NetMQ.Tests.csproj
  windows:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - run: dotnet restore src/NetMQ.sln
    - name: build
      run: dotnet build src/NetMQ.sln /p:Configuration=Release /verbosity:minimal
    - name: test net6.0
      run: dotnet test -v n -p:ParallelizeTestCollections=false --configuration Release --no-build -f net6.0 src\NetMQ.Tests\NetMQ.Tests.csproj
    - name: test net8.0
      run: dotnet test -v n -p:ParallelizeTestCollections=false --configuration Release --no-build -f net8.0 src\NetMQ.Tests\NetMQ.Tests.csproj
    - name: test net47
      run: dotnet test -v n -p:ParallelizeTestCollections=false --configuration Release --no-build -f net47 src\NetMQ.Tests\NetMQ.Tests.csproj
